### ISSUE TITLE
tagged releases?

### ISSUE THREAD

**Issue by anarcat** [ivpusic/grpool#10]
hi,

first, thank you for this software, it looks quite useful and is used in a tool I am packaging for debian ([dmarc-cat](https://github.com/keltia/dmarc-cat/)).

one problem with this dependency is that it doesn't have official releases. it makes it hard to find out when changes happen in the code base. it also makes tracking module dependencies with the new golang module system harder.

would you consider using official, tagged releases for your software?

again thank you for your time.

**Comment by ivpusic** [comment]
tnx for the suggestion. the first release is just introduced. https://github.com/ivpusic/grpool/releases/tag/v1.0.0. Next releases will follow semantic versioning and will describe new features/bugfixes in release notes.

**Comment by anarcat** [comment]
excellent, thanks for doing the right thing! :)
