### ISSUE TITLE
need fixes to run examples/first.go and examples/second.go

### ISSUE THREAD

**Issue by progamer71** [ivpusic/grpool#9]
@ivpusic I have to change
"package grpool" to "package main"
and
"func first() {" to "func main() {"
in examples/first.go to run command
go run src/github.com/ivpusic/grpool/examples/first.go

I also have to fix in the same way for examples/second.go

**Comment by ivpusic** [comment]
yes, they are not intended to be run as a program, but just to serve as an code example
